### ISSUE TITLE
Trying to see how to include this in place of http.server

### ISSUE THREAD

**Issue by jorvis** [danvk/RangeHTTPServer#17]
At the end of a larger python3 script I start an http.server but it's not meeting my needs because it doesn't support Range requests.  This appears to extend SimpleHttpServer and I'm struggling to see if I can incorporate it into my usage.  Currently I have these imports at the top of my [script](https://github.com/jorvis/GALES/blob/master/bin/view_annotation):

```
from http.server import BaseHTTPRequestHandler, HTTPServer
from http.server import CGIHTTPRequestHandler
```

And then can call my run() method to start the server when I need it:

```
def run(host=None, port=None, script_args=None):
    args = {'annotation_dir': script_args.input_directory, 'fasta_file': script_args.fasta_file}
    args_string = urllib.parse.urlencode(args)

    initial_url = "http://{0}:{1}/index.html?{2}".format(host, port, args_string)
    print("Starting GALESui server.  Open your browser to the following URL:\n\n{0}".format(initial_url), flush=True)
 
    # Server settings
    server_address = (host, port)
    handler = CGIHTTPRequestHandler
    handler.cgi_directories = ["/cgi"]
    httpd = HTTPServer(server_address, CGIHTTPRequestHandler)
    httpd.serve_forever()
```

Where does your ranged module fit here, or is this outside its scope?  Thanks for the help.

**Comment by jorvis** [comment]
If I import it and try to replace HTTPServer with RangeHTTPServer I get this:

```
Traceback (most recent call last):
  File "./view_annotation", line 301, in <module>
    main()
  File "./view_annotation", line 139, in main
    run(host=server_host, port=server_port, script_args=args)
  File "./view_annotation", line 278, in run
    httpd = RangeHTTPServer(server_address, CGIHTTPRequestHandler)
TypeError: 'module' object is not callable
```

**Comment by jorvis** [comment]
I got it to work by embedding part of your code within my app directly and making some changes to support the CGI response handler as the base class instead.

https://github.com/jorvis/GALES/commit/8cef4ffa79fb0eac7b608f97ac3163fe5778a548
